### ISSUE TITLE
Post forums integration of update-changelog action

### ISSUE THREAD

**Issue by zerok** [grafana/grafana-github-actions-go#37]
The original update-changelog action also posts to https://community.grafana.com/. This functionality is currently missing from the re-implementation here. See https://github.com/grafana/grafana/pull/66723 for the discussion around this.

The initial implementation should just copy the current behaviour *but* make it idempotent so that an existing post will be updated. We might move that behind a flag later on.

**Comment by zerok** [comment]
The code is mostly done but I'm currently trying to set up a testing environment so that I can be sure that the API calls do what they're supposed to without posting into community.grafana.com :D

**Comment by tleopold** [comment]
Investigate using commits to generate change log in an automated way
