### ISSUE TITLE
Update-changelog: Post limit to Community

### ISSUE THREAD

**Issue by zerok** [grafana/grafana-github-actions-go#41]
Discourse seems to have a maximum post size of 32,000 characters. If a changelog (like the one for 9.5.0) exceeds that limit, we need a way to truncate it in a usable manner.

@grafana/grafana-community-support what would be your preferred approach here?

**Comment by usmangt** [comment]
Hi @zerok,

We can increase the post size in the Discourse settings if required. Please let us know what size should be set.

**Comment by usmangt** [comment]
The limit is now increased to 50000 characters. For now, this should work but we can discuss if we run out in future :slightly_smiling_face:

**Comment by zerok** [comment]
@usmangt Thank you :) Trying again now :D

**Comment by zerok** [comment]
Worked, thank you :D
